data:
  image_path: null
  num_segments: 1
  num_strokes: 32
  is_closed: false
  width: 1.5
  radius: 0.05
  text_prompt: "minimalist vector art of a colorful rocket ship, icon, isolated on white background, digital art, trending on artstation."  # Not used if using CLIP loss
  text_prompt_suffix: ""
  negative_prompt: "oversaturated, pixelated, foggy, hazy, blurry, bad structure, noisy, malformed, watermark, zoom"
  generate_target_image: true
  attn_init_xdog_intersec: true
  use_background: false
log:
  allow_overwrite: true
  exp_name: experiment
  exp_root: ./experiments
  log2wandb: false
  visualization_truncation_idxs: [1,2,4,8,16,32,64,128,256,512]
model:
  mlp_dim: 128
  mlp_num_layers: 2
  text2img_model: stabilityai/stable-diffusion-2-1-base
  lora_weights: ./lora_weights/pytorch_lora_weights_sd21b_sketches.safetensors
  use_color: false
  use_nested_dropout: true
  nested_dropout_sampling_method: exp_decay  # 'weighted', 'uniform', 'custom', 'annealing', 'annealing_soft', 'exp_decay'
  input_dim: 128
  truncation_start_idx: 4
  use_dropout_value: true
  dropout_emb_dim: 16
  dropout_last_item_prob: 0.7
  dropout_temperature: 3
  toggle_color: false
  toggle_color_input_dim: 12
  toggle_color_bg_colors: ["light-red", "light-green", "light-blue", "gold", "gray"]
  toggle_color_method: "rgb"
  toggle_color_init_eps: 0.25
  toggle_sample_random_color_prob: 0

optim:  
  scheduler_type: LIN_RAMP_COS_DECAY  # SIN_RAMP_EXP_DECAY, LIN_RAMP_COS_DECAY
  learning_rate: 0.018 # 0.02  # Used also as 'lr_init' in ['SIN_RAMP_EXP_DECAY', 'LIN_RAMP_COS_DECAY']
  target_lr: 0.012
  learning_rate_pretrain: 0.01  # Used also as 'lr_init' in ['SIN_RAMP_EXP_DECAY', 'LIN_RAMP_COS_DECAY']
  warmup_steps: 200
  sds_weight: 'default'  # default, constant, noisematch, sdslike, strongerlower  | see https://github.com/JunzheJosephZhu/HiFA/blob/1bbe86135f960f4f99ab1f4c294bb5f4151da273/nerf/sd.py#L235

  # Clipping Grads
  clip_grad_max_norm_colors: 0.1
  clip_grad_max_norm_points: 0.01

steps:
  image_interval: 1000
  image_interval_pretrain: 100  # Pretrain changes quickly
  max_steps: 4000
  max_steps_pretrain: 100

seed: 42